# Generated by Django 4.2 on 2024-06-11 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_emailaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeEmailAddressToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public Identifier')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_change_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Change Token',
                'verbose_name_plural': 'Email Change Tokens',
                'ordering': ['-created_time'],
            },
        ),
    ]
