# Generated by Django 4.2 on 2024-06-12 10:45

import config.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_changeemailaddresstoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaluser',
            name='full_name',
            field=models.CharField(blank=True, max_length=60, null=True, validators=[config.validators.validate_full_name, django.core.validators.MinLengthValidator(5, message='Full name must be at least 5 characters long.')]),
        ),
    ]
