# Generated by Django 4.2 on 2024-05-30 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learner',
            old_name='account_created_by',
            new_name='account_maintained_by',
        ),
        migrations.RemoveField(
            model_name='learner',
            name='created_by',
        ),
    ]
