# Generated by Django 4.2 on 2024-05-29 06:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public Identifier')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('grade', models.CharField(max_length=11, verbose_name='Grade')),
                ('grade_ne', models.CharField(max_length=11, null=True, verbose_name='Grade')),
                ('in_symbol', models.CharField(max_length=3, verbose_name='Grade in Symbol')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grade',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public Identifier')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(max_length=11, verbose_name='Language')),
                ('language_ne', models.CharField(max_length=11, null=True, verbose_name='Language')),
                ('abbreviation', models.CharField(max_length=3, verbose_name='Abbreviation')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Language',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public Identifier')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=50, verbose_name='Subject')),
                ('subject_ne', models.CharField(max_length=50, null=True, verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subject',
            },
        ),
    ]
