# Generated by Django 4.2 on 2024-05-30 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('learner', '0001_initial'),
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='ClassRoom',
        ),
    ]
