# Generated by Django 4.2 on 2024-06-12 10:45

import config.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_remove_classroom_learners_classroom_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='title',
            field=models.CharField(max_length=255, validators=[config.validators.validate_class_room_name, django.core.validators.MinLengthValidator(5, message='Classroom title must be at least 5 characters long.')]),
        ),
    ]
