# Generated by Django 4.2 on 2024-05-29 09:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_grade_grade_en_language_language_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpaathModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public Identifier')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('chapter_id', models.CharField(max_length=25)),
                ('abstract', models.TextField()),
                ('thumbnail', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('is_published', models.BooleanField(default=False)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grade')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.language')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
            options={
                'verbose_name': 'E-Paath Module',
                'verbose_name_plural': 'E-Paath Modules',
            },
        ),
    ]
