# Generated by Django 4.2 on 2024-05-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epaath', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epaathmodules',
            name='is_published',
        ),
        migrations.AddField(
            model_name='epaathmodules',
            name='published',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3, verbose_name='published'),
        ),
    ]
